name: Lint
on: [push]
jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - name: Checkout 
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Lint
      uses: Compdog-inc/eslint-check-action@v1.1.1
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintFiles: "api"
        eslintConfig: ".eslintrc.json"
        eslintExt: "ts"
